version: "3.8"

volumes:
  grafana_data: {}
  prometheus_data: {}

networks:
  monitoring:

services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/config.yml
      - --storage.tsdb.path=/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    # ports:
    #   - "9100:9100"
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter
    # ports:
    #   - "9115:9115"
    volumes:
      - ./blackbox/config.yml:/etc/blackbox_exporter/config.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki
    networks:
      - monitoring

  promtail:
    image: grafana/promtail
    volumes:
      # custom config will read logs from the containers of
      # this project
      - ./promtail/config.yml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    # ports:
    #   - "8080:8080"
    networks:
      - monitoring